import { Opportunity, CommercialTask, SalesRep, Brand } from '@/types/crm';

export const INITIAL_BRANDS: Brand[] = ['NoLimits', 'Webissimo', 'Sapori'];

export const INITIAL_REPS: SalesRep[] = [
  { id: 'francesco', name: 'Francesco V.', role: 'Senior Closer', active: true },
  { id: 'marco', name: 'Marco T.', role: 'Enterprise Account', active: true },
  { id: 'elena', name: 'Elena B.', role: 'Key Account Specialist', active: true },
  { id: 'alessandro', name: 'Alessandro Rossi', role: 'Executive VP Sales (Admin)', active: true },
];

export const INITIAL_SERVICES: Record<string, string[]> = {
  NoLimits: ['Gestione Meta Ads', 'Campagne Google Ads ROI', 'Growth Hacking Funnel', 'TikTok B2B & Creator', 'SEO Scalata Organica'],
  Webissimo: ['Sviluppo E-Commerce Shopify Plus', 'Portale Web App Next.js', 'Restyling Brand & UI/UX', 'Integrazioni ERP/CRM'],
  Sapori: ['Food Marketing & Social Ho.Re.Ca', 'Menu Engineering & Margini', 'Lead Gen Franchising Food', 'Shooting & Packaging Gourmet'],
};

// Helper today format YYYY-MM-DD
const today = new Date().toISOString().split('T')[0];
const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];
const inThreeDays = new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0];

export const INITIAL_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'NL-8429',
    name: 'Dott. Mario Rossi',
    company: 'TechSpa S.r.l.',
    brand: 'NoLimits',
    service: 'Gestione Meta Ads',
    leadSource: 'Webinar B2B',
    salesRep: 'Francesco V.',
    phone: '+39 02 8934521',
    whatsapp: '+393401234567',
    email: 'm.rossi@techspa.it',
    value: 18500,
    valueType: 'One Shot',
    entryDate: '2026-09-25',
    stage: 'Trattativa',
    notes: 'Azienda software B2B con 40 dipendenti. Molto interessati a scalare lead generation su Meta e LinkedIn. Hanno già visto la prima demo.',
    dealHealthScore: 85,
    nextAction: {
      id: 'act-1',
      what: 'Richiamare dopo invio proposta tecnica per confermare budget trimestrale',
      who: 'Francesco V.',
      when: today,
      time: '14:30',
      type: 'chiamata',
      priority: 'Alta',
      completed: false,
    },
    history: [
      { id: 'h-1', date: '25/09', timestamp: '2026-09-25T10:00:00Z', title: 'Lead Inbound ricevuto da Form Webinar', type: 'task', author: 'System' },
      { id: 'h-2', date: '26/09', timestamp: '2026-09-26T15:30:00Z', title: 'Prima telefonata conoscitiva di qualifica', description: 'Budget approvato > 15k, decisore unico.', type: 'chiamata', author: 'Francesco V.' },
      { id: 'h-3', date: '29/09', timestamp: '2026-09-29T11:00:00Z', title: 'Video call Strategica con Direzione', description: 'Presentato piano NoLimits Growth. Feedback eccellente.', type: 'appuntamento', author: 'Francesco V.' },
      { id: 'h-4', date: '01/10', timestamp: '2026-10-01T17:00:00Z', title: 'Preventivo e Bozza Accordo inviati via Email', description: 'Valore €18.500 una tantum con opzione retainer €2.500/m.', type: 'preventivo', author: 'Francesco V.' },
    ],
  },
  {
    id: 'WB-3011',
    name: 'Giulia Bianchi',
    company: 'Atelier Moda Milano S.p.A.',
    brand: 'Webissimo',
    service: 'Sviluppo E-Commerce Shopify Plus',
    leadSource: 'Google Ads',
    salesRep: 'Marco T.',
    phone: '+39 02 7712390',
    whatsapp: '+393339876543',
    email: 'giulia.bianchi@ateliermoda.it',
    value: 34000,
    valueType: 'One Shot',
    entryDate: '2026-09-20',
    stage: 'Chiusura',
    notes: 'Progetto migrazione da Magento obsoleto a Shopify Plus headless. Hanno validato il layout UI/UX. In attesa di firma contrattuale.',
    dealHealthScore: 92,
    nextAction: {
      id: 'act-2',
      what: 'Inviare contratto finale con clausola SLA e pianificare kick-off',
      who: 'Marco T.',
      when: today,
      time: '11:00',
      type: 'preventivo',
      priority: 'Alta',
      completed: false,
    },
    history: [
      { id: 'h-10', date: '20/09', timestamp: '2026-09-20T09:00:00Z', title: 'Lead ricevuto da Campagna Search Webissimo', type: 'task', author: 'System' },
      { id: 'h-11', date: '22/09', timestamp: '2026-09-22T14:00:00Z', title: 'Discovery Call con Resp. IT e Marketing', type: 'appuntamento', author: 'Marco T.' },
      { id: 'h-12', date: '28/09', timestamp: '2026-09-28T16:00:00Z', title: 'Presentazione architettura tecnica e preventivo', type: 'preventivo', author: 'Marco T.' },
    ],
  },
  {
    id: 'SP-1092',
    name: 'Roberto Valente',
    company: 'Osteria Del Duca & Franchising',
    brand: 'Sapori',
    service: 'Menu Engineering & Margini',
    leadSource: 'Referral',
    salesRep: 'Elena B.',
    phone: '+39 051 445566',
    whatsapp: '+393481122334',
    email: 'r.valente@osteriadelduca.com',
    value: 4800,
    valueType: 'Mensile',
    entryDate: '2026-09-28',
    stage: 'Appuntamento',
    notes: 'Catena di 4 locali tipici in Emilia. Cercano ottimizzazione food cost e rilancio delivery con packaging custom.',
    dealHealthScore: 78,
    nextAction: {
      id: 'act-3',
      what: 'Video call con Chef e titolare per audit food-cost attuale',
      who: 'Elena B.',
      when: today,
      time: '16:00',
      type: 'appuntamento',
      priority: 'Media',
      completed: false,
    },
    history: [
      { id: 'h-20', date: '28/09', timestamp: '2026-09-28T11:00:00Z', title: 'Segnalato da cliente partner Sapori', type: 'task', author: 'Elena B.' },
      { id: 'h-21', date: '30/09', timestamp: '2026-09-30T10:30:00Z', title: 'Telefonata introduttiva e fissato audit', type: 'chiamata', author: 'Elena B.' },
    ],
  },
  {
    id: 'NL-9921',
    name: 'Luca Ferri',
    company: 'FinanzaFacile Fintech',
    brand: 'NoLimits',
    service: 'Growth Hacking Funnel',
    leadSource: 'Meta Ads',
    salesRep: 'Francesco V.',
    phone: '+39 06 6543210',
    whatsapp: '+393356789012',
    email: 'l.ferri@finanzafacile.co',
    value: 12000,
    valueType: 'One Shot',
    entryDate: '2026-09-15',
    stage: 'Stand-by',
    standbyReason: 'In attesa di approvazione nuovo round seed Q4 dagli investitori',
    standbyReactivationDate: today, // Arrivato oggi a data riattivazione!
    notes: 'Trattativa caldissima ma bloccata sul budget. Sveglia impostata per verifica arrivo fondi.',
    dealHealthScore: 60,
    nextAction: {
      id: 'act-4',
      what: 'Riattivazione Stand-by: verificare chiusura round investitori e sbloccare offerta',
      who: 'Francesco V.',
      when: today,
      time: '10:00',
      type: 'follow-up',
      priority: 'Alta',
      completed: false,
    },
    history: [
      { id: 'h-30', date: '15/09', timestamp: '2026-09-15T09:00:00Z', title: 'Lead entrato da Meta Ads', type: 'task', author: 'System' },
      { id: 'h-31', date: '18/09', timestamp: '2026-09-18T16:00:00Z', title: 'Demo e preventivo inviato €12.000', type: 'preventivo', author: 'Francesco V.' },
      { id: 'h-32', date: '22/09', timestamp: '2026-09-22T12:00:00Z', title: 'Messo in Stand-by fino al rilascio fondi Q4', type: 'task', author: 'Francesco V.' },
    ],
  },
  {
    id: 'WB-4412',
    name: 'Chiara Moretti',
    company: 'Studio Legale Moretti & Associati',
    brand: 'Webissimo',
    service: 'Portale Web App Next.js',
    leadSource: 'Inbound',
    salesRep: 'Marco T.',
    phone: '+39 011 234567',
    whatsapp: '+393498877665',
    email: 'chiara@morettilex.it',
    value: 15000,
    valueType: 'One Shot',
    entryDate: '2026-09-10',
    stage: 'Trattativa',
    notes: 'Portale clienti per consultazione fascicoli online con autenticazione SPID/CIE. Nessuna azione impostata recentemente!',
    dealHealthScore: 40,
    // INTENTIONALLY WITHOUT NEXT ACTION TO TEST REGOLA FONDAMENTALE & ALERTS!
    history: [
      { id: 'h-40', date: '10/09', timestamp: '2026-09-10T10:00:00Z', title: 'Richiesta preventivo da sito webissimo', type: 'task', author: 'System' },
      { id: 'h-41', date: '14/09', timestamp: '2026-09-14T15:00:00Z', title: 'Call tecnica requisiti portale', type: 'appuntamento', author: 'Marco T.' },
    ],
  },
  {
    id: 'SP-2201',
    name: 'Chef Antonio Cannavale',
    company: 'Pasticceria Vesuvio',
    brand: 'Sapori',
    service: 'Shooting & Packaging Gourmet',
    leadSource: 'Meta Ads',
    salesRep: 'Elena B.',
    phone: '+39 081 7654321',
    whatsapp: '+393281133557',
    email: 'info@pasticceriavesuvio.it',
    value: 8500,
    valueType: 'One Shot',
    entryDate: '2026-09-18',
    stage: 'Conoscenza',
    notes: 'Nuova linea di panettoni artigianali per Natale 2026. Necessità di packaging lusso e campagna influencer food.',
    dealHealthScore: 70,
    nextAction: {
      id: 'act-5',
      what: 'Inviare portfolio packaging natalizi realizzati da Sapori e listino prezzi',
      who: 'Elena B.',
      when: tomorrow,
      time: '09:30',
      type: 'whatsapp',
      priority: 'Media',
      completed: false,
    },
    history: [
      { id: 'h-50', date: '18/09', timestamp: '2026-09-18T14:20:00Z', title: 'Lead da Campagna Natale Food', type: 'task', author: 'System' },
      { id: 'h-51', date: '21/09', timestamp: '2026-09-21T11:00:00Z', title: 'Primo contatto WhatsApp e qualifica preliminare', type: 'whatsapp', author: 'Elena B.' },
    ],
  },
  {
    id: 'NL-7733',
    name: 'Andrea Galli',
    company: 'SolarGreen Solutions S.r.l.',
    brand: 'NoLimits',
    service: 'Campagne Google Ads ROI',
    leadSource: 'Google Ads',
    salesRep: 'Francesco V.',
    phone: '+39 039 998877',
    whatsapp: '+393475544332',
    email: 'a.galli@solargreen.com',
    value: 26000,
    valueType: 'Annuale',
    entryDate: '2026-09-02',
    stage: 'Venduta',
    winDate: '2026-09-29',
    notes: 'Contratto annuale firmato. Gestione campagne Google Ads Search + PMax impianti fotovoltaici industriali. Anticipo incassato.',
    dealHealthScore: 100,
    history: [
      { id: 'h-60', date: '02/09', timestamp: '2026-09-02T10:00:00Z', title: 'Lead qualificato inbound', type: 'task', author: 'System' },
      { id: 'h-61', date: '10/09', timestamp: '2026-09-10T16:00:00Z', title: 'Incontro di persona in sede cliente', type: 'appuntamento', author: 'Francesco V.' },
      { id: 'h-62', date: '20/09', timestamp: '2026-09-20T11:00:00Z', title: 'Accordo approvato e firmato digitalmente', type: 'task', author: 'Francesco V.' },
      { id: 'h-63', date: '29/09', timestamp: '2026-09-29T10:00:00Z', title: 'Vendita conclusa e prima tranche incassata', type: 'task', author: 'Francesco V.' },
    ],
  },
  {
    id: 'WB-1190',
    name: 'Stefania Rizzi',
    company: 'Immobiliare Panoramica',
    brand: 'Webissimo',
    service: 'Restyling Brand & UI/UX',
    leadSource: 'Referral',
    salesRep: 'Marco T.',
    phone: '+39 055 887766',
    whatsapp: '+393409988771',
    email: 'stefania@immobiliarepanoramica.it',
    value: 9500,
    valueType: 'One Shot',
    entryDate: '2026-08-20',
    stage: 'Persa',
    lossReason: 'Hanno scelto un fornitore locale a basso costo (freelance)',
    notes: 'Trattativa chiusa negativamente. Non avevano budget per qualità agency. Da ricontattare tra 6 mesi se non soddisfatti.',
    dealHealthScore: 10,
    history: [
      { id: 'h-70', date: '20/08', timestamp: '2026-08-20T09:30:00Z', title: 'Primo contatto referral', type: 'task', author: 'Marco T.' },
      { id: 'h-71', date: '05/09', timestamp: '2026-09-05T17:00:00Z', title: 'Trattativa persa per vincoli di budget', type: 'task', author: 'Marco T.' },
    ],
  },
  {
    id: 'NL-5544',
    name: 'Fabio Bernardi',
    company: 'Logistica Dinamica S.p.A.',
    brand: 'NoLimits',
    service: 'SEO Scalata Organica',
    leadSource: 'Outbound',
    salesRep: 'Francesco V.',
    phone: '+39 030 112233',
    whatsapp: '+393456677889',
    email: 'f.bernardi@logisticadinamica.it',
    value: 14400,
    valueType: 'Annuale',
    entryDate: '2026-09-12',
    stage: 'Trattativa',
    notes: 'Follow-up scaduto ieri! Dovevamo inviare l\'analisi competitor di posizionamento SEO.',
    dealHealthScore: 55,
    nextAction: {
      id: 'act-6',
      what: 'URGENTE: Chiamare cliente per scuse ritardo analisi competitor e fissare call di chiusura',
      who: 'Francesco V.',
      when: yesterday, // Expired follow-up to trigger automatic alert!
      time: '15:00',
      type: 'follow-up',
      priority: 'Alta',
      completed: false,
    },
    history: [
      { id: 'h-80', date: '12/09', timestamp: '2026-09-12T10:00:00Z', title: 'Contatto outbound via LinkedIn', type: 'task', author: 'Francesco V.' },
      { id: 'h-81', date: '18/09', timestamp: '2026-09-18T14:30:00Z', title: 'Call di approfondimento posizionamento Google', type: 'appuntamento', author: 'Francesco V.' },
    ],
  },
  {
    id: 'SP-8899',
    name: 'Davide Rinaldi',
    company: 'Ristorante Il Melograno',
    brand: 'Sapori',
    service: 'Lead Gen Franchising Food',
    leadSource: 'Webinar B2B',
    salesRep: 'Elena B.',
    phone: '+39 0521 889900',
    whatsapp: '+393391231234',
    email: 'd.rinaldi@ilmelogranofood.it',
    value: 22000,
    valueType: 'One Shot',
    entryDate: '2026-10-01',
    stage: 'Nuovo lead',
    notes: 'Nuovo lead appena registrato da webinar formativo. Hanno 2 format ristorativi pronti per espansione franchising.',
    dealHealthScore: 90,
    nextAction: {
      id: 'act-7',
      what: 'Primo contatto telefonico conoscitivo entro 24h per qualificare budget apertura affiliati',
      who: 'Elena B.',
      when: today,
      time: '17:30',
      type: 'chiamata',
      priority: 'Alta',
      completed: false,
    },
    history: [
      { id: 'h-90', date: '01/10', timestamp: '2026-10-01T18:00:00Z', title: 'Registrato da Webinar Food Strategy Sapori', type: 'task', author: 'System' },
    ],
  },
];

export const INITIAL_TASKS: CommercialTask[] = [
  {
    id: 'tsk-1',
    dealId: 'NL-8429',
    dealTitle: 'TechSpa S.r.l. - Dott. Mario Rossi',
    title: 'Richiamare Mario Rossi su preventivo Meta Ads',
    client: 'Dott. Mario Rossi',
    brand: 'NoLimits',
    assignedTo: 'Francesco V.',
    type: 'chiamata',
    priority: 'Alta',
    date: today,
    time: '14:30',
    description: 'Verificare approvazione budget trimestrale €18.500',
    status: 'Da fare',
  },
  {
    id: 'tsk-2',
    dealId: 'WB-3011',
    dealTitle: 'Atelier Moda - Giulia Bianchi',
    title: 'Inviare contratto Shopify Plus con clausola SLA',
    client: 'Giulia Bianchi',
    brand: 'Webissimo',
    assignedTo: 'Marco T.',
    type: 'preventivo',
    priority: 'Alta',
    date: today,
    time: '11:00',
    description: 'Inviare PDF siglato per firma digitale DocuSign',
    status: 'Da fare',
  },
  {
    id: 'tsk-3',
    dealId: 'SP-1092',
    dealTitle: 'Osteria Del Duca - Roberto Valente',
    title: 'Video Call Strategica: Audit Food-Cost & Margini',
    client: 'Roberto Valente',
    brand: 'Sapori',
    assignedTo: 'Elena B.',
    type: 'appuntamento',
    priority: 'Media',
    date: today,
    time: '16:00',
    meetingLink: 'https://meet.google.com/xyz-hubc-crm',
    description: 'Analisi distinta base e margini 4 locali',
    status: 'In corso',
  },
  {
    id: 'tsk-4',
    dealId: 'NL-9921',
    dealTitle: 'FinanzaFacile - Luca Ferri',
    title: 'Sveglia Stand-by: verifica chiusura round seed',
    client: 'Luca Ferri',
    brand: 'NoLimits',
    assignedTo: 'Francesco V.',
    type: 'standby-wake',
    priority: 'Alta',
    date: today,
    time: '10:00',
    description: 'Opportunità riattivata oggi dal letargo commerciale',
    status: 'Da fare',
  },
  {
    id: 'tsk-5',
    dealId: 'SP-8899',
    dealTitle: 'Ristorante Il Melograno - Davide Rinaldi',
    title: 'Primo contatto conoscitivo qualifica franchising',
    client: 'Davide Rinaldi',
    brand: 'Sapori',
    assignedTo: 'Elena B.',
    type: 'chiamata',
    priority: 'Alta',
    date: today,
    time: '17:30',
    description: 'Chiamata entro 24h per lead da Webinar Sapori',
    status: 'Da fare',
  },
  {
    id: 'tsk-6',
    dealId: 'NL-5544',
    dealTitle: 'Logistica Dinamica - Fabio Bernardi',
    title: 'Follow-up scaduto: spiegazione competitor SEO',
    client: 'Fabio Bernardi',
    brand: 'NoLimits',
    assignedTo: 'Francesco V.',
    type: 'follow-up',
    priority: 'Alta',
    date: yesterday,
    time: '15:00',
    description: 'Attività scaduta ieri da recuperare urgentemente',
    status: 'Da fare',
  },
  {
    id: 'tsk-7',
    dealId: 'SP-2201',
    dealTitle: 'Pasticceria Vesuvio - Chef Antonio Cannavale',
    title: 'Invio campionario packaging e catalogo natalizio',
    client: 'Chef Antonio Cannavale',
    brand: 'Sapori',
    assignedTo: 'Elena B.',
    type: 'whatsapp',
    priority: 'Media',
    date: tomorrow,
    time: '09:30',
    description: 'Messaggio WhatsApp business con link catalogo PDF',
    status: 'Da fare',
  },
];
