/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['variant', [
    '[data-theme="slate"] &',
    '[data-theme="oled"] &',
    '.dark &',
    ':root:not([data-theme="light"]) &'
  ]],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-dim': 'var(--surface-dim)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'inverse-surface': 'var(--inverse-surface)',
        'surface-bright': 'var(--surface-bright)',
        'primary': 'var(--primary)',
        'secondary-fixed-dim': 'var(--secondary-fixed-dim)',
        'on-tertiary-fixed-variant': 'var(--on-tertiary-fixed-variant)',
        'outline': 'var(--outline)',
        'on-tertiary': 'var(--on-tertiary)',
        'secondary-container': 'var(--secondary-container)',
        'outline-variant': 'var(--outline-variant)',
        'error-container': 'var(--error-container)',
        'primary-container': 'var(--primary-container)',
        'on-secondary-container': 'var(--on-secondary-container)',
        'on-primary-fixed-variant': 'var(--on-primary-fixed-variant)',
        'tertiary': 'var(--tertiary)',
        'background': 'var(--background)',
        'on-primary-fixed': 'var(--on-primary-fixed)',
        'error': 'var(--error)',
        'surface-tint': 'var(--surface-tint)',
        'on-error-container': 'var(--on-error-container)',
        'inverse-on-surface': 'var(--inverse-on-surface)',
        'surface-container-high': 'var(--surface-container-high)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'on-tertiary-fixed': 'var(--on-tertiary-fixed)',
        'primary-fixed-dim': 'var(--primary-fixed-dim)',
        'on-secondary-fixed-variant': 'var(--on-secondary-fixed-variant)',
        'on-secondary': 'var(--on-secondary)',
        'on-tertiary-container': 'var(--on-tertiary-container)',
        'secondary-fixed': 'var(--secondary-fixed)',
        'surface-container': 'var(--surface-container)',
        'on-primary': 'var(--on-primary)',
        'primary-fixed': 'var(--primary-fixed)',
        'on-error': 'var(--on-error)',
        'secondary': 'var(--secondary)',
        'surface': 'var(--surface)',
        'inverse-primary': 'var(--inverse-primary)',
        'tertiary-fixed': 'var(--tertiary-fixed)',
        'on-background': 'var(--on-background)',
        'tertiary-fixed-dim': 'var(--tertiary-fixed-dim)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'surface-variant': 'var(--surface-variant)',
        'on-secondary-fixed': 'var(--on-secondary-fixed)',
        'on-surface': 'var(--on-surface)',
        'tertiary-container': 'var(--tertiary-container)',
        'on-primary-container': 'var(--on-primary-container)',
        'surface-container-low': 'var(--surface-container-low)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'margin-sm': '1rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'margin': '2rem',
        'gutter-lg': '2rem',
        'space-sm': '0.5rem',
        'space-xl': '2.5rem',
        'margin-lg': '3rem',
        'gutter-sm': '1rem',
        'space-xs': '0.25rem',
        'gutter': '1.5rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        headline: ['"Plus Jakarta Sans"', 'sans-serif'],
        mono: ['monospace'],
      },
    },
  },
  plugins: [],
};
